version: "3"
services:
  client:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./aws-mqtt:/var/app/aws-mqtt
      - ./thing:/var/app/thing
    command: ['python3']
