version: 0.2

phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - kubectl version --short --client
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPO_URI=659821968821.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/enres-confluent-poc
      - BUILD_TAG="$(date +%Y%m%d%H%M%S)_$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_TAG=${USED_TAG:-$BUILD_TAG}
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker pull $REPO_URI:$NAMESPACE || true
      - docker build --cache-from $REPO_URI:$NAMESPACE -t $REPO_URI:$NAMESPACE -t $REPO_URI:$BUILD_TAG .
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Pushing latest the Docker images...
      - docker push $REPO_URI:$NAMESPACE
      - echo Pushing commit sha the Docker images...
      - docker push $REPO_URI:$BUILD_TAG
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME

      - echo Apply confluent-depl;
      - sed -i -e "s/{{ IMAGE_TAG }}/$IMAGE_TAG/g" deploy/k8s/12-confluent-depl.yaml;
      - sed -i -e "s/{{ NAMESPACE }}/$NAMESPACE/g" deploy/k8s/12-confluent-depl.yaml;
      - sed -i -e "s/{{ NODEGROUP_NAME }}/$NODEGROUP_NAME/g" deploy/k8s/12-confluent-depl.yaml;
      - kubectl apply -f deploy/k8s/12-confluent-depl.yaml;
